#"Environment for training Goose model with Pointcept + CUDA 11.8"
#Uses pytorch version 2.1.0 and i let the cudnn version be inferred or something

[workspace]
authors = ["Ethan M <marque6@clemson.edu>"]
channels = ["nvidia/label/cuda-11.8.0", "nvidia", "pytorch", "conda-forge", "pyg"]
name = "merged_goose_reno_Jul18"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

#[tasks.install-scatter]
#cmd = "bash scripts/install_scatter.sh"

[tasks.install-scatter]
cmd = "pip install torch-scatter -f https://data.pyg.org/whl/torch-2.2.0+cu121.html"

[tasks.install-flash-attn]
#pip install flash-attn==2.7.0.post2
cmd = "pip install flash-attn --no-build-isolation"

[tasks.install-clip]
cmd = "pip install git+https://github.com/openai/CLIP.git"

[dependencies]
python = "3.9.*"
ipykernel = "*"
h5py = "*"
pyyaml = "*"
sharedarray = "*"
tensorboard = "*"
tensorboardx = "*"
yapf = "*"
addict = "*"
einops = "*"
plyfile = "*"
termcolor = "*"
timm = "*"
pytorch-cluster = "*"
pytorch-sparse = "*"
gcc = "9.5.*"
gxx = "9.5.*"
pytorch = "==2.1.0"
torchvision = "*"
torchaudio = "*"
pip = "*"
cudatoolkit = "11.8.*"
cuda = { version = "11.8.*", channel = "nvidia" }
cuda-nvcc = { version = "11.8.*", channel = "nvidia" }
#cudnn = { version = "8.*", channel = "nvidia" }
scipy = "*"

sparsehash = ">=2.0.4,<3"

[pypi-dependencies]
ninja = "*"
torch-geometric = "*"
spconv-cu118 = "*"
ftfy = "*"
regex = "*"
tqdm = "*"
wandb = ">=0.20.1, <0.21"
typing_extensions = "==4.12.2"
pathlib = "*"

torchac = ">=0.9.3, <0.10"
open3d = ">=0.18.0, <0.19"
rootpath = ">=0.1.1, <0.2"
pyarrow = ">=20.0.0, <21"
fastparquet = ">=2024.11.0, <2025"